apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
        {{- include "account-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
        {{- include "account-service.selectorLabels" . | nindent 4 }}
